### ISSUE TITLE
git tracking branch error

### ISSUE THREAD

**Issue by anandnalya** [sbt/sbt-release#100]
Hi,

I'm trying to do a sbt-release from the master branch on jenkins but getting the following error:

    [info] Starting release process off commit: 338bf143888957344045af2999a9bba38bac6e57
    java.lang.RuntimeException: No tracking branch is set up. Either configure a remote tracking branch, or remove the pushChanges release part.

Following is the output of `git remote show origin`

    showing remote tracking
    Warning: Permanently added '[stash]:7999,[172.21.230.9]:7999' (RSA) to the list of known hosts.
    * remote origin
      Fetch URL: ssh://git@stash:7999/~analya/docker-test.git
      Push  URL: ssh://git@stash:7999/~analya/docker-test.git
      HEAD branch: master
      Local ref configured for 'git push':
        master pushes to master (up to date)

Am I missing something here?

**Comment by anandnalya** [comment]
For some reason, jenkins git was not setting the following properties which I had to do as a pre-built step

    git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
    git config branch.master.remote origin
    git config branch.master.merge refs/heads/master

**Comment by prayagupd** [comment]
Based on sbt-release code - https://github.com/sbt/sbt-release/blob/3368d0086c2d6e869bab8b5a2ddef530a39dabbd/src/main/scala/ReleaseExtra.scala#L215 `--set-upstream` followed by `sbt release` worked for me,

```bash
git push --set-upstream origin CURRENT_BRANCH_NAME
sbt release 
```
