### ISSUE TITLE
Versions such as X.Y.Z.N are disallowed, which is totally arbitrary

### ISSUE THREAD

**Issue by 2rs2ts** [sbt/sbt-release#101]
I tried to release a version of my software 0.6.9.1, but got this:

    java.lang.RuntimeException: Version format is not compatible with ([0-9]+)(?:(?:\.([0-9]+))?(?:\.([0-9]+))?)?([\-0-9a-zA-Z]*)?

I don't think there's any reason to impose only major, minor, and micro. I like doing "nano" releases, personally.

**Comment by 2rs2ts** [comment]
Or let me put it this way, the scheme provided by semver.org is too restrictive and I don't think this plugin should follow it.

**Comment by dpdearing** [comment]
I created a fork that allows "nano" (and smaller) subrelease version numbers at https://github.com/dpdearing/sbt-release

**Comment by 2rs2ts** [comment]
@dpdearing Cool! Do you plan on opening a PR?

**Comment by dpdearing** [comment]
@2rs2ts just created pull request #125

**Comment by 2rs2ts** [comment]
The PR was merged; closing.
