### ISSUE TITLE
merging changes to master

### ISSUE THREAD

**Issue by mpryahin** [sbt/sbt-release#129]
Hi guys!
I'm little bit stuck with plugin usage. Is it possible to merge all changes made in develop branch to the master while releasing? Currently tags are being created based on the develop branch.

Lets say I need something like this:
1. change the project version to release version and push those changes to the remote develop branch
2. merge the latest develop commit to the master branch and tag it.
3. change the version number to the next snapshot and push those changes back to the remote develop

So can I achieve this?

Thank you in advance!

**Comment by jroper** [comment]
You could easily write your own release step to do that.
