### ISSUE TITLE
use defaults instead of passing "with-defaults" each time

### ISSUE THREAD

**Issue by mohamedkomalo** [sbt/sbt-release#134]
I wanted to use the defaults of the release process without passing "with-defaults" each time to the "release" command, but I couldn't find a way.

is this currently supported or not ?

**Comment by jozic** [comment]
Alias?

**Comment by mohamedkomalo** [comment]
Thanks I didn't know about command aliases, I can use addCommandAlias to alias "release with-defaults" but I need the name of the alias to be "release", so I can't use it

I wanted to know if there's settingsKey I can use to set it by default inside the build, I have tried using ReleaseKeys.useDefaults but it is an AttributeKey and I couldn't find much info about it

**Comment by mohamedkomalo** [comment]
As @jozic said, command alias can be used

build.sbt example

```scala
lazy val myproject = (project in file("myproject")).
  settings(
    addCommandAlias("releaseSilent", "release with-defaults")
)
```

Another option would be to create another command to override the release command

build.sbt example
```scala
lazy val myproject = (project in file("myproject")).
  settings(
    commands += Command.command("release") { state =>
      // note the usage the releaseCommand.parser instead of "state.combinedParser" parser
      Parser.parse(" with-defaults", ReleaseKeys.releaseCommand.parser(state)) match {
        case Right(cmd) => cmd()
        case Left(msg) => throw sys.error(s"Error triggering release command:\n$msg")
      }
    }
  )
```
