### ISSUE TITLE
Does not close + release on nexus

### ISSUE THREAD

**Issue by johnynek** [sbt/sbt-release#136]
My teammates don't see this issue, but have to manually close and release. It does upload correctly.

I get this message:
```
[info] Nexus repository URL: https://oss.sonatype.org/service/local
[info] sonatypeProfileName = posco
[info] Reading staging repository profiles...
[warn] No staging repository is found. Do publishSigned first.
```

**Comment by jroper** [comment]
`sbt-release` knows nothing about the Sonatype OSS repository (and nor should it), so of course it's not going to close and release for you.  You have to either do that manually, or add a step in the release steps to do it.  If you're using `sbt-sonatype`, here's an example of how you can add that step to the release steps:

https://github.com/jroper/play-iteratees-extras/blob/master/build.sbt#L49

**Comment by johnynek** [comment]
I am using `sbt-sonatype` and I have:

https://github.com/twitter/scalding/blob/develop/build.sbt#L136
`ReleaseStep(action = Command.process("sonatypeReleaseAll", _)),`

which is what someone with a multiproject repo, like ours in scalding, has. Should that not work?

Again, on the same project coworkers have this working. I am seeing some kind of error as I pasted above: `[warn] No staging repository is found. Do publishSigned first.`

**Comment by jroper** [comment]
We have a multi project repo with Play, and this is the config we use (`interplay` is an sbt plugin that provides sbt config common to all Play projects, including the main Play repo itself):

https://github.com/playframework/interplay/blob/master/src/main/scala/interplay/PlayBuildBase.scala#L221

You shouldn't need `sonatypeReleaseAll`, `sonatypeRelease` should be enough.  Try logging in to the sonatype UI and see what the status of thinsg are, is there an open profile?

**Comment by johnynek** [comment]
yes, there is an open profile. I have to manually close and release it.

**Comment by johnynek** [comment]
by the way, what is the difference with Release and ReleaseAll? This page seems to say we need ReleaseAll for cross builds, which we do:

https://github.com/xerial/sbt-sonatype
