### ISSUE TITLE
Support signing Git tags & commits

### ISSUE THREAD

**Issue by larsrh** [sbt/sbt-release#154]
This would be very useful given that GitHub now [recognizes PGP signatures](https://github.com/blog/2144-gpg-signature-verification).

**Comment by larsrh** [comment]
(If the maintainers are interested I can take a stab at implementing this.)

**Comment by jroper** [comment]
Of course, you're welcome to take a stab at it. This project isn't actively maintained by anyone, every few months (or when someone hassles me) I take a look at the open pull requests, merge a few things and cut a release.

**Comment by larsrh** [comment]
@jroper See now #165. A new release with this would be appreciated :smile:
