### ISSUE TITLE
ReleaseExtra.runTaskAggregated would be useful as a public function

### ISSUE THREAD

**Issue by gregsymons** [sbt/sbt-release#156]
When writing a release precheck, I may want to execute a task on all submodules and then look at the results from each submodule. Currently the `checkSnapshotDependencies` uses a private function (`ReleaseExtra.runTaskAggregated`) to run an aggregated task, and gets back the new `State` and a `Seq` with the task results from each aggregated submodule. It would be useful if there was a similar public API.

**Comment by gregsymons** [comment]
I'm not 100% sure that `runTaskAggregated` as written is necessarily the best API for this, but something like it would be nice.

**Comment by xuwei-k** [comment]
https://github.com/sbt/sbt-release/commit/245db6a9abfb7bb8a315867e6ebbf0a09a7a31a2
