### ISSUE TITLE
[question] How to Disable 'sbt-release' Versioning Commits?

### ISSUE THREAD

**Issue by kevinmeredith** [sbt/sbt-release#160]
After running `sbt release`, where I select `n` for pushing changes, I ran:

```
$git log
 hash a: Setting version to 0.4.1-SNAPSHOT
 hash b: Setting version to 0.4.0
 hash c: my changes
```

Typically, I just run: `git rebase -i HEAD~3`, and then squash `a` and `b`.

How can I disable commits `a` and `b` so that I can avoid the rebasing step?

Lastly - thanks for this tool! I've found it very helpful.

**Comment by gseitz** [comment]
You have to setup your own release process. There's a section on this topic in the [README](https://github.com/sbt/sbt-release#no-git-and-no-toy-projects).
