### ISSUE TITLE
`runClean` results in `ivy not found error`

### ISSUE THREAD

**Issue by jvican** [sbt/sbt-release#172]
Imagine the following publish settings:

``` scala
lazy val publishSettings = Seq(
  publishMavenStyle := true,
  bintrayOrganization := Some("scalaplatform"),
  bintrayRepository := "tools",
  bintrayPackageLabels := Seq("scala", "platform", "tools", "sbt"),
  publishTo := (publishTo in bintray).value,
  publishArtifact in Test := false,
  releasePublishArtifactsAction := PgpKeys.publishSigned.value,
  licenses := Seq(
    // Scala Center license... BSD 3-clause
    "BSD" -> url("http://opensource.org/licenses/BSD-3-Clause")
  ),
  homepage := Some(url("https://github.com/scalaplatform/platform")),
  autoAPIMappings := true,
  apiURL := Some(url("https://scalaplatform.github.io/platform")),
  scmInfo := Some(
    ScmInfo(
      url("https://github.com/scalaplatform/platform"),
      "scm:git:git@github.com:scalaplatform/platform.git"
    )
  ),
  releaseProcess := Seq[ReleaseStep](
    checkSnapshotDependencies,
    inquireVersions,
    runTest,
    setReleaseVersion,
    commitReleaseVersion,
    tagRelease,
    publishArtifacts,
    setNextVersion,
    commitNextVersion,
    pushChanges
  ),
  pomExtra :=
    <developers>
      <developer>
        <id>jvican</id>
        <name>Jorge Vicente Cantero</name>
        <url></url>
      </developer>
    </developers>
)
```

This release pipeline is problematic for sbt setups with differents subprojects. Executing`runClean` before `runTest` has an unexpected effect in `publishArtifacts`: it _somehow_ changes the state, `deliver` does nothing and the following error appears:

```
[error] (release-manager/*:deliver) java.lang.IllegalStateException: Ivy file not found in cache for ch.epfl.scala#release-manager_2.11;0.2!
[error] Total time: 16 s, completed Oct 19, 2016 3:26:48 PM
```

Something must be going on under the hood, because removing `runClean` from the pipeline makes my release process works. The funny thing is that executing `clean` in the sbt console, followed by`release`, works. So I wonder if this is something related to `sbt` internals...

I will provide a link to reproduce such issue soon, since the project I'm working on hasn't been open-sourced yet.

**Comment by jvican** [comment]
Closing, this seems to be an error of sbt in multi-project builds when `clean` is used. I may report it to sbt/sbt.

**Comment by adelbertc** [comment]
@jvican I think I'm running into this as well - did you ever follow-up with SBT?

**Comment by jvican** [comment]
No, please file the issue. This is a serious problem that I experience most every day.

**Comment by dwijnand** [comment]
I think I know what this is. If it's the same thing @alexarchambault was telling me about it goes something like this: `deliver` depends on files generated by `update`...... -.-

**Comment by jvican** [comment]
Note to myself: I owe a big beer to whomever fixes this.

**Comment by alexarchambault** [comment]
I confirm I ran into this kind of issue with sbt-coursier. I had to have sbt-coursier generate some xml files from `update` for `deliver` to be fine later on. These are currently generated by [this method](https://github.com/coursier/coursier/blob/114d2f95ad71bd1ba8fcb702267586f40e9f412b/sbt-coursier/src/main/scala-2.10/coursier/IvyXml.scala#L11). A few versions ago (`< 1.0.0-M15`?), this file was not always re-generated (after a clean in particular), which lead to the same kind of issue as bove.

**Comment by jvican** [comment]
I actually think this issue may be related to sbt holding references onto previous ivy files that when cleaned are removed recursively and are not cleared in sbt's side. It happens very frequently with sbt scripted.

**Comment by adamw** [comment]
I'm also getting this. Removing coursier fixed the problem

**Comment by alexarchambault** [comment]
@adamw The issue here is not related to coursier.

**Comment by adamw** [comment]
@alexarchambault ah indeed :) I was using RC8. Thanks!
