### ISSUE TITLE
Publish 1.0.5

### ISSUE THREAD

**Issue by andreaTP** [sbt/sbt-release#196]
I think since there are a few commits that are merged and not published yet, I believe it's time to kindly publish it :-)

Thanks in advance

**Comment by andreaTP** [comment]
please, any update?

**Comment by andreaTP** [comment]
ok, I believe this is going a bit too far...
I kindly ask to the owners of the sbt organization ( @eed3si9n @dwijnand @jroper @jvican ) to clearly say if this project is still maintained or not.

In this case I haven't asked for any modifications, just a matter of running a couple of sbt commands and I'm still waiting any kind of feedback/answer since one month.

Thanks a lot in advance.

**Comment by jvican** [comment]
The Scala Center doesn't own this project, so I cannot comment @andreaTP.

**Comment by andreaTP** [comment]
I added you to the list @jvican since you are listed as a member in sbt org in github ... :-)

**Comment by leonardehrenfried** [comment]
This project hasn't had updates for a while and seems to be stagnating.

It should be possible to find someone who'd be willing to maintain this plugin but who would you talk to to gain write access? Or is a complete fork the only option?

**Comment by dwijnand** [comment]
Done! The nice thing about releasing sbt-release is that it's pre-configured, so it was really easy.

https://github.com/sbt/sbt-release/releases/tag/v1.0.5

**Comment by andreaTP** [comment]
thanks a lot!
