### ISSUE TITLE
Support SBT 1.0

### ISSUE THREAD

**Issue by spockz** [sbt/sbt-release#198]
SBT 1.0.0-M5 was released. It would be nice if sbt-release supported that version of sbt.

**Comment by leonardehrenfried** [comment]
I tried it the other day and it's more than a simple recompilation. There are incompatibilities between the sbt versions so code has to be moved into version-specific files. Urgh.

**Comment by xuwei-k** [comment]
- https://dl.bintray.com/sbt/sbt-plugin-releases/com.github.gseitz/sbt-release/scala_2.12/sbt_1.0/1.0.6/
- https://bintray.com/sbt/sbt-plugin-releases/sbt-release/1.0.6
