### ISSUE TITLE
`sbt release` double-publishes Java projects if crossScalaVersions is set

### ISSUE THREAD

**Issue by wsargent** [sbt/sbt-release#219]
From https://github.com/sbt/sbt/issues/3431#issuecomment-364234627, using

```
addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.7")
```

with `sbt.version=1.1.0`

If you have an AutoPlugin:

```scala
import sbt.Keys._
import sbt._

object CommonSettings extends AutoPlugin {
  override def trigger = allRequirements

  override lazy val projectSettings = Seq(
    scalaVersion := "2.12.4",
    crossScalaVersions := Seq("2.11.6", "2.12.4"),
    libraryDependencies += "org.scalatest" %% "scalatest" % "3.0.4" % Test,
    fork in run := true,
    fork in Test := true
  ) 
}
```

 It turns out that when you add `crossScalaVersions`, when you have a Java only project

```

lazy val `dynamiclogging` = project
  .in(file("dynamiclogging"))
  .settings(disableDocs)
  .settings(
    name := "dynamiclogging",

    // Used for java-only publishing
    releaseCrossBuild := false,
    crossPaths := false,
    autoScalaLibrary := false,

    javacOptions in (Compile, doc) ++= javacSettings,
    javacOptions in Test ++= javacSettings,

    libraryDependencies += "com.typesafe" % "config" % "1.3.2",
    libraryDependencies += "org.slf4j" % "slf4j-api" % "1.7.25",
    libraryDependencies += "ch.qos.logback" % "logback-classic" % "1.2.3",
    libraryDependencies += "com.udojava" % "JMXWrapper" % "1.4",
  )
```

 then sbt-release will always try to publish it twice: even if you set it to Nil, even if you set releaseCrossBuild := false in the Java project, etc.  Then you get:

```
java.io.IOException: destination file exists and overwrite == false
```

on the second attempt, and the `sbt release` dies mid publish, without pushing the version.sbt modification.

Only way to stop double publishing is to remove crossScalaVersions as a setting applied to all projects.

**Comment by richdougherty** [comment]
Hi @wsargent, I'm getting a similar problem in `play-ws`, so I have a few questions about your workaround for this.

> sbt-release will always try to publish it twice: even if you set it to Nil

So just to clarify, you're seeing this if crossScalaVersions is set to Nil. I guess you've also tried setting it to Seq("2.12.4") and it didn't work?

> Only way to stop double publishing is to remove crossScalaVersions as a setting applied to all projects

How did you do this? Did you remove crossScalaVersions as a setting from the AutoPlugin then explicitly add it into the projects you need? I can't see a way to remove the setting explicitly...

**Comment by wsargent** [comment]
> Did you remove crossScalaVersions as a setting from the AutoPlugin then explicitly add it into the projects you need?

Yes.

**Comment by richdougherty** [comment]
OK thanks. I haven't been able to get this fixed - I probably need to start from a simpler project and work incrementally. Anyway, still an issue for play-ws right now.

**Comment by eed3si9n** [comment]
Not sure if this is generally applicable, but I think I was able to fix play-ws - https://github.com/playframework/play-ws/pull/243/commits/945a6f489592e5daf4338e5e5c0a361e88d54951

**Comment by plokhotnyuk** [comment]
IMO source of double-publishing is in the `publish` task which packs 2 sets of artifacts for different patch versions of Scala.
In my case that were 2.12.6 and 2.12.7 versions and here is how I fixed it: 
https://github.com/plokhotnyuk/jsoniter-scala/commit/aa493d3d0848ededf5b8c4d295c671236a5031a3

**Comment by wsargent** [comment]
Thanks -- I ran into this again and it was super annoying.

I have a sample project in https://github.com/wsargent/shade-with-sbt-assembly that also demos the issue.

**Comment by wsargent** [comment]
Also see https://github.com/wsargent/sbt-release-with-javasubproject

**Comment by eed3si9n** [comment]
I think this is a general cross publishing documentation issue, which I think https://github.com/sbt/website/pull/750 should address.

https://github.com/wsargent/sbt-release-with-javasubproject/pull/1 _should_ demonstrate the fix.

**Comment by wsargent** [comment]
@eed3si9n wsargent/sbt-release-with-javasubproject#1 publishes, but it does not compile or test the subprojects -- sbt-release does not perform operations without `crossScalaVersions` being set in the root project.

**Comment by wsargent** [comment]
@eed3si9n FYI https://github.com/sbt/website/pull/750 should probably be changed to match up with https://github.com/wsargent/sbt-release-with-javasubproject/pull/2 as that's where the fix is.

**Comment by eed3si9n** [comment]
I can add a note about it, but really the bug is in sbt-release's fake cross implementation that was copy-pasted from sbt 0.13.

**Comment by eed3si9n** [comment]
https://github.com/sbt/website/pull/757
