### ISSUE TITLE
turn `euro` to `dollar`

### ISSUE THREAD

**Issue by kjcaputa** [sbt/sbt-release#226]
Hi all,
  I am just wondering if it is correct or not, but better to turn somebody's eyes on build.sbt
Is it correct to have the **`€` Euro char** in the line 40 of build.sbt instead of **`$` dollar**?
https://github.com/sbt/sbt-release/blob/23956070ba07953a20c442d24f283421d37e7c31/build.sbt#L40
```
scalacOptions in (Compile, doc) ++= {
  val tag = tagOrHash.value
  Seq(
    "-sourcepath", (baseDirectory in LocalRootProject).value.getAbsolutePath,
    "-doc-source-url", s"https://github.com/sbt/sbt-release/tree/${tag}€{FILE_PATH}.scala"
  )
}
```

**Comment by dwijnand** [comment]
Yep! It's correct: https://stackoverflow.com/a/10423118/463761.

**Comment by kjcaputa** [comment]
Cheers, for explanation. Good to know that.
