### ISSUE TITLE
Artifactory repo unavailable

### ISSUE THREAD

**Issue by eboto** [sbt/sbt-release#23]
Hello. The listed repository (http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases) is 404ed, where other artifactoryonline repos seem to be online. Is this still the right place to get sbt-release artifacts?

**Comment by rohitgupta-90** [comment]
https://scalasbt.artifactoryonline.com/ is still down, I am consistently getting 404 for last 2 days, are there any plans to resolve this?
