### ISSUE TITLE
How to access version number in running app

### ISSUE THREAD

**Issue by LukeDefeo** [sbt/sbt-release#245]
Is it possible to define a custom release step that takes the current version (after setting it in setReleaseVersion) and then write this version to a file in the resources directory (accessible to the app) with just the following content 

```
1.2.3
```

then in my api i can read this resource file and add this version as a header so i can be sure what version is running in production.

Any other ways to solve my problem would be appreciated.

**Comment by tanishiking** [comment]
You may you want to use https://github.com/sbt/sbt-buildinfo ?
