### ISSUE TITLE
releaseCommitMessage not honored for next version

### ISSUE THREAD

**Issue by Kevin-Covey** [sbt/sbt-release#256]
This is somewhat related to [issue 186](https://github.com/sbt/sbt-release/issues/186).  We have a build process that is kicked off via git hooks, and the commits done by the release plugin start a chain of endless job runs.  We can tell the build pipeline to ignore commits by putting `[ci skip]` in the commit message, so I configured my build with `releaseCommitMessage := s"[ci skip] Setting version to ${(version in ThisBuild).value}"`.  This works for the commit where we go from a snapshot version to the release version, but not when going from the release version to the next snapshot version.  Examples of the commit messages I end up with are `[ci skip] Setting version to 1.0.5` followed by `Setting version to 1.0.6-SNAPSHOT`.

Having both commits honor my config (which it seems like it should do) would fix the issue, but being able to disable git hooks as requested in issue 186 would be a more direct way to get to where I'm trying to go.

**Comment by akozich** [comment]
New property `releaseNextCommitMessage` has been introduced recently for next iteration message. See https://github.com/sbt/sbt-release/commit/e1abd0a62072ca803636829b7fa0812ef67e59a1

**Comment by Kevin-Covey** [comment]
Awesome, that's just what I needed.  I opened PR 257 to add this property to the README.
