### ISSUE TITLE
publish to maven central instead of bintray. change maven groupId?

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt-release#271]
https://github.com/sbt/sbt/issues/6294
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

- keep `com.github.gseitz` ?
- `com.github.sbt` like https://github.com/sbt/sbt-pgp/commit/0aefa74dac80397537ef3c9bbc12a06183f65053 ?
- any other groupId (e.g. `com.github.xuwei-k`) ?

🤔 

/cc @eed3si9n @gseitz

**Comment by eed3si9n** [comment]
Since you're the effective maintainer, it's up to you.
If you want to use `com.github.sbt`, I'd be happy to set the credential as secret so it can use sbt-ci-release.

**Comment by xuwei-k** [comment]
Thanks. I want to use `com.github.sbt`. Please set credential 🙏 

https://github.com/sbt/sbt-release/settings/secrets/actions

**Comment by eed3si9n** [comment]
Done.

**Comment by xuwei-k** [comment]
![a](https://user-images.githubusercontent.com/389787/108456665-237ce700-72b4-11eb-8451-0bcae4f09ccf.png)

https://github.com/olafurpg/sbt-ci-release/tree/767a819e0b71462250af9273a74f7099a7d6ec4c#secrets

missing `PGP_PASSPHRASE` and `PGP_SECRET` 🤔

**Comment by eed3si9n** [comment]
I think any fresh key would do. I just created one and set one for this repo.
