### ISSUE TITLE
Github release notes are not updated and are inconsistent

### ISSUE THREAD

**Issue by Andrapyre** [sbt/sbt-release#400]
Github releases do not include most versions that have been released. Some releases are taking release notes from the `notes` folder while others are generated on the spot. 

At minimum, the last two releases `v1.3` and `v1.4` should have release notes, especially`v1.4` which included some small breaking changes and method deprecations of which users should be aware.

**Comment by Andrapyre** [comment]
@eed3si9n , happy to help on this if needed. I can create a PR to the `notes` folder and you can generate the Github release from that.

Just let me know.

**Comment by eed3si9n** [comment]
Yea, I was gonna create a release for this.

**Comment by eed3si9n** [comment]
https://github.com/sbt/sbt-release/releases/tag/v1.4.0

**Comment by Andrapyre** [comment]
Ah ok, perfect, thanks! Could releases be included in the `About` section so that they are visible on the homepage?

**Comment by eed3si9n** [comment]
Done
