### ISSUE TITLE
Version number not trimming off SNAPSHOT for package, and publishers not evaluated correctly

### ISSUE THREAD

**Issue by samus42** [sbt/sbt-release#94]
1) I see the -SNAPSHOT getting trimmed off for the tag, that works fine, however the jar that get's built still has the -SNAPSHOT version on there, and it is using that when attempting to publish.  I.e. it publishes to:
http://localhost/repositories/monsanto-tps-snapshots/com/darkthorn/test/sbt-artifact-test_2.10/1.0.3-SNAPSHOT/

That last dir should be 1.0.3.

2) I have a different publisher for snapshots than for releases, and i use the standard if statement for the publishTo setting.  However, as shown in the above example, it's not picking the right one (always picking the snapshot one), it's probably related to #1.  

My SBT file is as follows:
name := "sbt-artifact-test"

version := "1.0.3-SNAPSHOT"

organization := "com.darkthorn.test"

scalaVersion := "2.10.4"

libraryDependencies ++= Seq(
    "org.scalatest" %% "scalatest" % "2.2.1" % "test"
)

publishTo := {
    val nexusRoot = "http://localhost/"
    val releasesUrl = s"$nexusRoot/repositories/monsanto-tps"
    if (isSnapshot.value)
        Some("Snapshots" at s"$releasesUrl-snapshots")
    else
        Some("Releases" at releasesUrl)
}

releaseSettings

**Comment by gseitz** [comment]
You need to use `version in ThisBuild := "..."` in `version.sbt`. See https://github.com/sbt/sbt-release#versionsbt
