### ISSUE TITLE
Error codes should return proper error codes

### ISSUE THREAD

**Issue by joprice** [sbt/sbt-release#95]
When sbt fails to compile, `echo "$?"` returns 1. However, when for example, the publish step fails because the version is already published and overwrite is not set, the exit code is 0. This causes a CI server's publish script to consider the task a success.

**Comment by rossabaker** [comment]
I posted an [example project](https://github.com/rossabaker/sbt-release-exit-code) that demonstrates this.  I see this if the last release step fails.  If I add a release step after the failing step, I see the expected short circuiting and non-zero exit code.

**Comment by xuwei-k** [comment]
1.0.8 released https://github.com/sbt/sbt-release/compare/v1.0.7...v1.0.8

**Comment by andreaTP** [comment]
YAY!
