### ISSUE TITLE
Release version from command arguments

### ISSUE THREAD

**Issue by rikardNL** [sbt/sbt-release#96]
Hi,

The reason for this issue is that I want to know the viability of a pull request I have in mind. If this seems like a good idea I will create a pull request for a suggested implementation. If this is not the please for such a discussion, please direct me elsewhere.

Case:
I am setting up a parametrised build in Jenkins using this release plugin with a customised release flow. My team have a special way of working with versions where the version in our code is always at 0-SNAPSHOT. (For more information on our way of working with versions see this blog post: http://axelfontaine.com/blog/final-nail.html)

Problem:
This leads to the with-defaults flag not making sense and since we want to used a parametrised build in Jenkins we can't use the inquireVersions ReleaseStep. 

Solutions:
Instead I would like to supply the version as an argument of the sbt release command like "sbt release with-defaults version=1.0.0". In this case the default value for releaseVersion as derived from the current version in inquireVersion would be replaced by 1.0.0.

What do you think?

**Comment by gseitz** [comment]
Hi, 
That's a very useful feature that is still missing. A pull request would be much appreciated.
It'd be good if both versions (release version, next version) are supported via a parameter.

**Comment by rikardNL** [comment]
Thanks for the quick response. I will look into that later today.

**Comment by rikardNL** [comment]
FYI: We ended solving this in another way temporarily. Will get back to this in the future but have more urgent issues at the moment.

**Comment by blake-boesinger** [comment]
@rikardNL I'd be interested in knowing how you solved this temporarily. Thanks, Blake

**Comment by rikardNL** [comment]
@blake-boesinger We put our version in a separate file version.sbt containing only the version like this: `version in ThisBuild := "0-SNAPSHOT"`.
 In Jenkins, after pulling the latest version and before compiling it we rewrite the current version to this file using a bash script as a build step in Jenkins. We get the release version from the github release tag available to the Jenkins github plugin. After this we continue as usual with the release build.

**Comment by laysakura** [comment]
Seems like this issue is totally resolved by #112
