### ISSUE TITLE
sbt release with-default still requires inputting the version

### ISSUE THREAD

**Issue by j-martin** [sbt/sbt-release#97]
Scala 2.11.5
sbt 0.13.7 (and 0.13.1)

The `with-defaults` option doesn't seem to work. As I am getting prompted to confirm the version. This currently causes to fail in TeamCity.

I added `releaseSettings` to build.sbt and the plugin. Other than everything works fine interactively.

```
$ sbt release with-defaults
[info] Loading project definition from /Users/<repo_path>/project
[warn] Multiple resolvers having different access mechanism configured with same name 'sbt-plugin-releases'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
[info] Set current project to estimation-service (in build file:/Users/<repo_path>/)
[info] Starting release process off commit: c56d826f520b406764b9351d02302a067b569ed5
[info] Checking remote [origin] ...
Release version [0.3] : java.lang.RuntimeException: No version provided!
	at scala.sys.package$.error(package.scala:27)
 	at sbtrelease.ReleaseStateTransformat
        [...]
```

**Comment by j-martin** [comment]
Well, it wasn't a bug after all. Using proper quotes solved the issue `sbt 'release with defaults'`.

**Comment by damirv** [comment]
Yes, but I noticed that ./activator 'release with-defaults' does not work (it still asks for the version). This used to work with `v1.0.0`, any idea why it fails `v1.0.2`?

**Comment by rosscdh** [comment]
+1
